# Generated by Django 4.0.2 on 2022-02-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0004_delete_serveradminproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Обноление Серверов',
                'verbose_name_plural': 'Обноление Серверов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.server',),
        ),
    ]
