# Generated by Django 4.0.2 on 2022-02-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_applicationserversspecification_and_more'),
        ('dictionary', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfoAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': '!СЕРВИС СЕРВЕРОВ',
                'verbose_name_plural': '!СЕРВИСЫ СЕРВЕРОВ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.applicationservers',),
        ),
        migrations.CreateModel(
            name='AppInfoAProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Сервисы',
                'verbose_name_plural': 'Сервисы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.application',),
        ),
        migrations.CreateModel(
            name='InstalledSoftInfoAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Установленные программы',
                'verbose_name_plural': 'Установленные программы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.hostinstalledsoftware',),
        ),
        migrations.CreateModel(
            name='ServerInfoAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': '!СЕРВЕР',
                'verbose_name_plural': '!СЕРВЕРА',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.server',),
        ),
        migrations.CreateModel(
            name='SoftInfoAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Программы',
                'verbose_name_plural': 'Программы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dictionary.softwarecatalog',),
        ),
    ]
