# Generated by Django 4.0.2 on 2022-04-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_applicationserversspecification_options_and_more'),
        ('reports', '0002_appinfoadminproxy_appinfoaproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationServersSpecificationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Назначение серверов',
                'verbose_name_plural': 'Назначение серверов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.applicationserversspecification',),
        ),
        migrations.CreateModel(
            name='SpecificationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Назначение серверов',
                'verbose_name_plural': 'Назначение серверов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.applicationserversspecification',),
        ),
    ]
