# Generated by Django 4.0.2 on 2022-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_daemonsadminproxy_futureadminproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfoadminproxy',
            options={'verbose_name': '!СЕРВІСИ СЕРВЕРІВ', 'verbose_name_plural': '!СЕРВІСИ СЕРВЕРІВ'},
        ),
        migrations.AlterModelOptions(
            name='appinfoaproxy',
            options={'verbose_name': 'Сервіси', 'verbose_name_plural': 'Сервіси'},
        ),
        migrations.AlterModelOptions(
            name='applicationserversspecificationproxy',
            options={'verbose_name': 'Призначення сервера', 'verbose_name_plural': 'Призначення серверів'},
        ),
        migrations.AlterModelOptions(
            name='daemonsadminproxy',
            options={'verbose_name': 'Служба', 'verbose_name_plural': 'Служби'},
        ),
        migrations.AlterModelOptions(
            name='futureadminproxy',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Ролі'},
        ),
        migrations.AlterModelOptions(
            name='installedsoftinfoadminproxy',
            options={'verbose_name': 'Встановленне ПЗ', 'verbose_name_plural': 'Встановлення ПЗ'},
        ),
        migrations.AlterModelOptions(
            name='serveradminproxy',
            options={'verbose_name': 'Обнолення Серверів', 'verbose_name_plural': 'Обнолення Серверів'},
        ),
        migrations.AlterModelOptions(
            name='serverinfoadminproxy',
            options={'verbose_name': '!СЕРВЕР', 'verbose_name_plural': '!СЕРВЕРИ'},
        ),
        migrations.AlterModelOptions(
            name='softinfoadminproxy',
            options={'verbose_name': 'Програми', 'verbose_name_plural': 'Програми'},
        ),
        migrations.AlterModelOptions(
            name='specificationproxy',
            options={'verbose_name': 'Призначення сервера', 'verbose_name_plural': 'Призначення серверів'},
        ),
    ]
