# Generated by Django 4.0.2 on 2022-08-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_remove_server_is_online_server_status'),
        ('reports', '0006_inlinemodelapplicationserversproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTaskAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Заплановані Задачі',
                'verbose_name_plural': 'Заплановані Задачі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.hostscheduledtask',),
        ),
    ]
