# Generated by Django 4.0.2 on 2023-02-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_appinfoadminproxy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfoaproxy',
            options={'verbose_name': '2. ЗВІТ "ПОРТАЛИ"', 'verbose_name_plural': '2. ЗВІТ "ПОРТАЛИ"'},
        ),
        migrations.AlterModelOptions(
            name='serveradminproxy',
            options={'verbose_name': 'Обновлення Серверів', 'verbose_name_plural': 'Обновлення Серверів'},
        ),
        migrations.AlterModelOptions(
            name='serverinfoadminproxy',
            options={'verbose_name': '1. Сервери', 'verbose_name_plural': '1. Сервери'},
        ),
    ]
