# Generated by Django 4.1.7 on 2023-03-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_serverresponse_options_and_more'),
        ('reports', '0009_alter_appinfoaproxy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPProxy',
            fields=[
            ],
            options={
                'verbose_name': 'IP та мережі',
                'verbose_name_plural': 'IP та мережі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dictionary.ip',),
        ),
        migrations.AlterModelOptions(
            name='appinfoaproxy',
            options={'verbose_name': '2. Сервіси', 'verbose_name_plural': '2. Сервіси'},
        ),
        migrations.AlterModelOptions(
            name='daemonsadminproxy',
            options={'verbose_name': 'Служба (Service)', 'verbose_name_plural': 'Служби (Service)'},
        ),
        migrations.AlterModelOptions(
            name='serveradminproxy',
            options={'verbose_name': 'Оновлення Серверів', 'verbose_name_plural': 'Оновлення Серверів'},
        ),
    ]
