# Generated by Django 4.2.5 on 2023-09-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_hostscheduledtask_schedule_type'),
        ('reports', '0010_ipproxy_alter_appinfoaproxy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHardwareInfoAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': '    Конфігурації серверів',
                'verbose_name_plural': 'Конфігурація сервера',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('info.configuration',),
        ),
    ]
