# Generated by Django 4.2.5 on 2023-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_serverhardwareinfoadminproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSStateReports_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Звіт про стан ОС',
                'verbose_name_plural': 'Звіт про стан ОС',
                'abstract': False,
                'managed': False,
            },
        ),
    ]
