# Generated by Django 4.0.2 on 2022-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_ip_mask_serverroom_net_masks_alter_serverroom_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Запланована задача')),
                ('display_name', models.CharField(max_length=200, verbose_name='Назва')),
                ('execute_path', models.CharField(max_length=255, verbose_name='Путь до скрипту')),
                ('silent', models.BooleanField(default=False, verbose_name='Приховане значення')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Автоматична задача',
                'verbose_name_plural': 'Автоматичні задачі',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('name',), 'verbose_name': 'Домен', 'verbose_name_plural': 'Домени'},
        ),
        migrations.AlterModelOptions(
            name='serverfuture',
            options={'ordering': ('name',), 'verbose_name': 'Роль', 'verbose_name_plural': 'Ролі'},
        ),
        migrations.AlterModelOptions(
            name='serverresponse',
            options={'ordering': ('name',), 'verbose_name': 'Відповідальність', 'verbose_name_plural': 'Відповідальності'},
        ),
        migrations.AlterModelOptions(
            name='serverrole',
            options={'ordering': ('name',), 'verbose_name': 'Призначення серверу', 'verbose_name_plural': 'Призначення серверів'},
        ),
        migrations.AlterModelOptions(
            name='serverroom',
            options={'ordering': ('name',), 'verbose_name': 'Серверна кімната', 'verbose_name_plural': 'Серверні кімнати'},
        ),
        migrations.AlterModelOptions(
            name='serverservice',
            options={'ordering': ('name',), 'verbose_name': 'Сервіс', 'verbose_name_plural': 'Сервіси'},
        ),
        migrations.AlterModelOptions(
            name='softwarecatalog',
            options={'ordering': ('name',), 'verbose_name': 'Програма', 'verbose_name_plural': 'Програми'},
        ),
        migrations.AddField(
            model_name='serverfuture',
            name='silent',
            field=models.BooleanField(default=False, verbose_name='Приховане значення'),
        ),
        migrations.AddField(
            model_name='serverservice',
            name='silent',
            field=models.BooleanField(default=False, verbose_name='Приховане значення'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ім`я домену'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP адреса'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='mask',
            field=models.PositiveIntegerField(default=32, verbose_name='Маска'),
        ),
        migrations.AlterField(
            model_name='os',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва ОС'),
        ),
        migrations.AlterField(
            model_name='serverfuture',
            name='display_name',
            field=models.CharField(max_length=200, verbose_name='Опис ролі'),
        ),
        migrations.AlterField(
            model_name='serverfuture',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Роль сервера'),
        ),
        migrations.AlterField(
            model_name='serverresponse',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Відповідальність'),
        ),
        migrations.AlterField(
            model_name='serverrole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='serverrole',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Призначення сервера'),
        ),
        migrations.AlterField(
            model_name='serverroom',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва серверної кімнати'),
        ),
        migrations.AlterField(
            model_name='serverroom',
            name='net_masks',
            field=models.ManyToManyField(blank=True, null=True, related_name='room', to='dictionary.IP', verbose_name='Мережеві маски, що використовуються у серверній'),
        ),
        migrations.AlterField(
            model_name='serverservice',
            name='display_name',
            field=models.CharField(max_length=200, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='serverservice',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Сервіс'),
        ),
        migrations.AlterField(
            model_name='softwarecatalog',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Назва програми'),
        ),
    ]
