# Generated by Django 4.0.2 on 2022-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_serverfuture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrole',
            name='silent',
            field=models.BooleanField(default=False, verbose_name='Приховане значення'),
        ),
    ]
