# Generated by Django 4.0.2 on 2022-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_serverrole_silent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverfuture',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Опис ролі'),
        ),
        migrations.AlterField(
            model_name='serverroom',
            name='net_masks',
            field=models.ManyToManyField(blank=True, related_name='room', to='dictionary.IP', verbose_name='Мережеві маски, що використовуються у серверній'),
        ),
        migrations.AlterField(
            model_name='serverscheduledtask',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Запланована задача'),
        ),
        migrations.AlterField(
            model_name='serverservice',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Опис'),
        ),
        migrations.AlterUniqueTogether(
            name='serverscheduledtask',
            unique_together={('name', 'execute_path')},
        ),
    ]
