# Generated by Django 4.0.2 on 2023-02-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_alter_serverfuture_display_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarecatalog',
            options={'ordering': ('name',), 'verbose_name': 'Програма (Soft Name)', 'verbose_name_plural': 'Програми (Softs Name)'},
        ),
        migrations.AddField(
            model_name='ip',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Коментар'),
        ),
    ]
