# Generated by Django 4.0.2 on 2023-02-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_alter_softwarecatalog_options_ip_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverservice',
            options={'ordering': ('name',), 'verbose_name': 'Служба (Service)', 'verbose_name_plural': 'Служби (Service)'},
        ),
    ]
