# Generated by Django 4.1.7 on 2023-03-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_alter_serverservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverresponse',
            options={'ordering': ('name',), 'verbose_name': 'Відповіmiдальність', 'verbose_name_plural': 'Відповідальності'},
        ),
        migrations.AddField(
            model_name='serverscheduledtask',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Код задачі для контролю'),
        ),
    ]
