# Generated by Django 4.1.7 on 2023-03-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_serverresponse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverscheduledtask',
            name='short_desc',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Короткій опис'),
        ),
        migrations.AlterField(
            model_name='serverscheduledtask',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Код задачі для контролю'),
        ),
    ]
