# Generated by Django 4.1.7 on 2023-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_serverscheduledtask_short_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverscheduledtask',
            name='full_actions',
            field=models.TextField(blank=True, null=True, verbose_name='Дії'),
        ),
        migrations.AlterField(
            model_name='serverscheduledtask',
            name='execute_path',
            field=models.CharField(max_length=2048, verbose_name='Путь до скрипту'),
        ),
        migrations.AlterField(
            model_name='serverscheduledtask',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Запланована задача'),
        ),
        migrations.AlterField(
            model_name='serverscheduledtask',
            name='short_desc',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Короткій опис'),
        ),
    ]
