# Generated by Django 4.2.5 on 2023-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_serverscheduledtask_full_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='family',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Сімейство ОС'),
        ),
    ]
