# Generated by Django 4.2.5 on 2023-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_os_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='old',
            field=models.BooleanField(default=False, verbose_name='Застаріла'),
        ),
    ]
