# Generated by Django 4.0.2 on 2022-02-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinstalledsoftware',
            name='server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.server', verbose_name='Сервер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='installed_soft',
            field=models.ManyToManyField(blank=True, null=True, related_name='servers', through='info.HostInstalledSoftware', to='info.SoftwareCatalog'),
        ),
        migrations.AlterUniqueTogether(
            name='hostinstalledsoftware',
            unique_together={('soft', 'server')},
        ),
    ]
