# Generated by Django 4.0.2 on 2022-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_update_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Последние апдейт'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='В эксплеатации'),
        ),
        migrations.AlterField(
            model_name='serverrole',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
