# Generated by Django 4.0.2 on 2022-02-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservers',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dictionary.serverrole', verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
