# Generated by Django 4.0.2 on 2022-02-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('info', '0002_applicationservers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationservers',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.serverresponse', verbose_name='Ответственнность'),
        ),
        migrations.AlterField(
            model_name='applicationservers',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.serverrole', verbose_name='Роль'),
        ),
    ]
