# Generated by Django 4.0.2 on 2022-02-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_hostinstalledsoftware_server_server_installed_soft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='responsible',
            field=models.ManyToManyField(to='info.ResponsiblePerson'),
        ),
        migrations.AlterField(
            model_name='server',
            name='applications',
            field=models.ManyToManyField(related_name='servers', to='info.Application'),
        ),
        migrations.AlterField(
            model_name='server',
            name='installed_soft',
            field=models.ManyToManyField(related_name='servers', through='info.HostInstalledSoftware', to='info.SoftwareCatalog'),
        ),
        migrations.AlterField(
            model_name='server',
            name='roles',
            field=models.ManyToManyField(related_name='servers', to='info.ServerRole'),
        ),
    ]
