# Generated by Django 4.0.2 on 2022-02-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_application_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinstalledsoftware',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Софт удален'),
        ),
        migrations.AddField(
            model_name='hostinstalledsoftware',
            name='last_check_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки'),
        ),
        migrations.CreateModel(
            name='ServerModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.server', verbose_name='Сервер')),
            ],
        ),
    ]
