# Generated by Django 4.0.2 on 2022-02-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_hostinstalledsoftware_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os_update_search',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего обнолвения'),
        ),
        migrations.AlterField(
            model_name='server',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='servers', to='info.Application'),
        ),
        migrations.AlterField(
            model_name='server',
            name='installed_soft',
            field=models.ManyToManyField(blank=True, related_name='servers', through='info.HostInstalledSoftware', to='info.SoftwareCatalog'),
        ),
        migrations.AlterField(
            model_name='server',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='servers', to='info.ServerRole'),
        ),
    ]
