# Generated by Django 4.0.2 on 2022-02-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('info', '0004_delete_serveradminproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationServersSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterModelOptions(
            name='applicationservers',
            options={'ordering': ('server__name', 'application__name'), 'verbose_name': 'Сервер для Приложения', 'verbose_name_plural': 'Сервера для Приложения'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ('server__name', 'platform_name'), 'verbose_name': 'Конфигурация', 'verbose_name_plural': 'Конфигурации'},
        ),
        migrations.AlterModelOptions(
            name='diskconfiguration',
            options={'ordering': ('configuration__server__name', 'pool_name'), 'verbose_name': 'Диск', 'verbose_name_plural': 'Диски'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('domain', 'name'), 'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.RemoveField(
            model_name='applicationservers',
            name='response',
        ),
        migrations.RemoveField(
            model_name='applicationservers',
            name='role',
        ),
        migrations.AddField(
            model_name='applicationservers',
            name='specifications',
            field=models.ManyToManyField(blank=True, through='info.ApplicationServersSpecification', to='dictionary.ServerRole', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='application',
            name='monitoring_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Мониторинг url'),
        ),
        migrations.AlterField(
            model_name='application',
            name='responsible',
            field=models.ManyToManyField(blank=True, to='info.ResponsiblePerson'),
        ),
        migrations.AlterField(
            model_name='application',
            name='worked_servers',
            field=models.ManyToManyField(blank=True, related_name='applications', through='info.ApplicationServers', to='info.Server'),
        ),
        migrations.AlterField(
            model_name='applicationservers',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_server', to='info.application', verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='applicationservers',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_info', to='info.server', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='diskconfiguration',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='info.configuration'),
        ),
        migrations.AlterField(
            model_name='diskconfiguration',
            name='hdd_size',
            field=models.PositiveIntegerField(default=0, verbose_name='HDD, Gb'),
        ),
        migrations.AlterField(
            model_name='diskconfiguration',
            name='hdd_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'SATA HDD'), (1, 'SAS HDD'), (2, 'SATA SSD'), (3, 'M2 SSD'), (50, 'Virtual')], null=True, verbose_name='Тип диска'),
        ),
        migrations.AlterField(
            model_name='diskconfiguration',
            name='raid_type',
            field=models.PositiveIntegerField(choices=[(0, 'SATA HDD'), (1, 'SAS HDD'), (2, 'SATA SSD'), (3, 'M2 SSD'), (50, 'Virtual')], default=999, verbose_name='Тип RAID'),
        ),
        migrations.AlterField(
            model_name='hostinstalledsoftware',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_soft', to='info.server', verbose_name='Сервер'),
        ),
        migrations.AlterField(
            model_name='hostinstalledsoftware',
            name='soft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='dictionary.softwarecatalog', verbose_name='Программа'),
        ),
        migrations.AddField(
            model_name='applicationserversspecification',
            name='application_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.applicationservers', verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='applicationserversspecification',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.serverresponse', verbose_name='Ответственнность'),
        ),
        migrations.AddField(
            model_name='applicationserversspecification',
            name='response_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.responsibleperson', verbose_name='Отвественный сотрудник'),
        ),
        migrations.AddField(
            model_name='applicationserversspecification',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.serverrole', verbose_name='Роль'),
        ),
    ]
