# Generated by Django 4.0.2 on 2022-04-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        ('info', '0005_applicationserversspecification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationserversspecification',
            options={'verbose_name': 'Зона ответственности', 'verbose_name_plural': 'Зоны ответственности'},
        ),
        migrations.AlterField(
            model_name='applicationservers',
            name='specifications',
            field=models.ManyToManyField(blank=True, through='info.ApplicationServersSpecification', to='dictionary.ServerRole', verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='applicationserversspecification',
            name='application_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='info.applicationservers', verbose_name='Назначение'),
        ),
    ]
