# Generated by Django 4.0.2 on 2022-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_serverservice'),
        ('info', '0006_alter_applicationserversspecification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='daemons',
            field=models.ManyToManyField(blank=True, related_name='servers', to='dictionary.ServerService'),
        ),
    ]
