# Generated by Django 4.0.2 on 2022-08-01 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_serverscheduledtask_alter_domain_options_and_more'),
        ('info', '0007_server_daemons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'verbose_name': 'Додаток', 'verbose_name_plural': 'Додаток'},
        ),
        migrations.AlterModelOptions(
            name='applicationservers',
            options={'ordering': ('server__name', 'application__name'), 'verbose_name': 'Сервер для додатка', 'verbose_name_plural': 'Сервера для додатка'},
        ),
        migrations.AlterModelOptions(
            name='applicationserversspecification',
            options={'verbose_name': 'Зона відповідальності', 'verbose_name_plural': 'Зони відповідальності'},
        ),
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ('server__name', 'platform_name'), 'verbose_name': 'Конфигурація', 'verbose_name_plural': 'Конфигурації'},
        ),
        migrations.AlterModelOptions(
            name='hostinstalledsoftware',
            options={'ordering': ('server__name', 'soft__name'), 'verbose_name': 'Встановлене ПО', 'verbose_name_plural': 'Встановлене ПО'},
        ),
        migrations.AlterModelOptions(
            name='responsibleperson',
            options={'ordering': ('name',), 'verbose_name': 'Відповідальні особи', 'verbose_name_plural': 'Відповідальні особи'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('domain', 'name'), 'verbose_name': 'Сервер', 'verbose_name_plural': 'Сервери'},
        ),
        migrations.AddField(
            model_name='application',
            name='depends',
            field=models.ManyToManyField(blank=True, related_name='dependencies', to='info.Application', verbose_name='Залежить від'),
        ),
        migrations.AddField(
            model_name='application',
            name='external',
            field=models.BooleanField(default=False, verbose_name='Опублікована в Інтернет'),
        ),
        migrations.AddField(
            model_name='hostinstalledsoftware',
            name='silent',
            field=models.BooleanField(default=False, verbose_name='Приховане значення'),
        ),
        migrations.AddField(
            model_name='server',
            name='external',
            field=models.BooleanField(default=False, verbose_name='Опублікований в Інтернет'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='application',
            name='monitoring_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Моніторінг url'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Назва додатка'),
        ),
        migrations.AlterField(
            model_name='applicationservers',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_server', to='info.application', verbose_name='Додаток'),
        ),
        migrations.AlterField(
            model_name='applicationservers',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='applicationservers',
            name='specifications',
            field=models.ManyToManyField(blank=True, through='info.ApplicationServersSpecification', to='dictionary.ServerRole', verbose_name='Призначення'),
        ),
        migrations.AlterField(
            model_name='applicationserversspecification',
            name='application_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='info.applicationservers', verbose_name='Призначенн'),
        ),
        migrations.AlterField(
            model_name='applicationserversspecification',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='applicationserversspecification',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.serverresponse', verbose_name='Відповідальність'),
        ),
        migrations.AlterField(
            model_name='applicationserversspecification',
            name='response_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.responsibleperson', verbose_name='Відповідальний співробітник'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='diskconfiguration',
            name='hdd_type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'SATA HDD'), (1, 'SAS HDD'), (2, 'SATA SSD'), (3, 'M2 SSD'), (50, 'Virtual')], null=True, verbose_name='Тип диску'),
        ),
        migrations.AlterField(
            model_name='hostinstalledsoftware',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата встановлення'),
        ),
        migrations.AlterField(
            model_name='hostinstalledsoftware',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='ПО видалено'),
        ),
        migrations.AlterField(
            model_name='hostinstalledsoftware',
            name='last_check_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата перевірики'),
        ),
        migrations.AlterField(
            model_name='hostinstalledsoftware',
            name='soft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installs', to='dictionary.softwarecatalog', verbose_name='Додаток'),
        ),
        migrations.AlterField(
            model_name='hostinstalledsoftware',
            name='version',
            field=models.CharField(max_length=200, verbose_name='Версія'),
        ),
        migrations.AlterField(
            model_name='responsibleperson',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='ФІО'),
        ),
        migrations.AlterField(
            model_name='responsibleperson',
            name='role',
            field=models.CharField(max_length=200, verbose_name='Кваліфікації'),
        ),
        migrations.AlterField(
            model_name='server',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Запис створено'),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='server',
            name='has_internet_access',
            field=models.BooleanField(default=False, verbose_name='Має вихід в інтернет'),
        ),
        migrations.AlterField(
            model_name='server',
            name='has_monitoring_agent',
            field=models.BooleanField(default=False, verbose_name='Відслідковується агентом'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='В експлуатації'),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_update_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Останній апдейт'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ім`я сервера'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_installed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Система встановлена'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час останнього оновлення'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_update_search',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час останнього пошуку оновлень'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Версія ОС'),
        ),
        migrations.AlterField(
            model_name='server',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_uses', to='info.server', verbose_name='Змінено на'),
        ),
        migrations.AlterField(
            model_name='server',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.serverroom', verbose_name='Серверна'),
        ),
        migrations.AlterField(
            model_name='server',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Запис оновлена'),
        ),
        migrations.AlterField(
            model_name='server',
            name='virtual_server_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ім`я виртуальної машини'),
        ),
    ]
