# Generated by Django 4.0.2 on 2022-08-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_serverfuture_options_and_more'),
        ('info', '0008_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200, verbose_name='Версія')),
                ('installation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата встановлення')),
                ('last_check_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата перевірики')),
                ('is_removed', models.BooleanField(default=False, verbose_name='ПО видалено')),
            ],
            options={
                'verbose_name': 'Заплановані задачі',
                'verbose_name_plural': 'Запланована задача',
                'ordering': ('server__name', 'task__name'),
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'verbose_name': 'Сервіс', 'verbose_name_plural': 'Сервіс'},
        ),
        migrations.AlterModelOptions(
            name='hostinstalledsoftware',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='hostinstalledsoftware',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='server',
            name='scheduled_tasks',
            field=models.ManyToManyField(blank=True, related_name='task_servers', through='info.HostScheduledTask', to='dictionary.ServerScheduledTask'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_task', to='info.server', verbose_name='Сервер'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dictionary.serverscheduledtask', verbose_name='Додаток'),
        ),
        migrations.RemoveField(
            model_name='hostinstalledsoftware',
            name='silent',
        ),
        migrations.AlterUniqueTogether(
            name='hostscheduledtask',
            unique_together={('task', 'server')},
        ),
    ]
