# Generated by Django 4.0.2 on 2022-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_serverfuture_options_and_more'),
        ('info', '0009_hostscheduledtask_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostinstalledsoftware',
            options={'verbose_name': 'ПО встановлено на сервері', 'verbose_name_plural': 'ПО встановлено на сервері'},
        ),
        migrations.RemoveField(
            model_name='hostscheduledtask',
            name='version',
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='exit_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Останній код виконання'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата останього запуску'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата наступного запуску'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='run_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='schedule',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Повторення'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='schedule_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип Повторення'),
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='hostscheduledtask',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Задачу видалено'),
        ),
        migrations.AlterUniqueTogether(
            name='hostinstalledsoftware',
            unique_together={('soft', 'server')},
        ),
    ]
