# Generated by Django 4.0.2 on 2022-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_hostinstalledsoftware_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='is_online',
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(0, 'Вимкнено'), (1, 'В роботі'), (2, 'Видалено'), (3, 'В резерві'), (4, 'Не ініціалізовано')], default=1, verbose_name='Стан'),
        ),
    ]
