# Generated by Django 4.0.2 on 2023-02-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_remove_server_is_online_server_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'verbose_name': '2. Портал\\Додаток', 'verbose_name_plural': '2. Портали\\Додатки'},
        ),
        migrations.AlterModelOptions(
            name='applicationservers',
            options={'ordering': ('server__name', 'application__name'), 'verbose_name': '3. Сервер для додатка', 'verbose_name_plural': '3. Сервера для додатка'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ('domain', 'name'), 'verbose_name': '1. Сервер', 'verbose_name_plural': '1. Сервери'},
        ),
    ]
