# Generated by Django 4.0.2 on 2023-02-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'verbose_name': '2. Сервіс', 'verbose_name_plural': '2. Сервіс'},
        ),
        migrations.AlterModelOptions(
            name='applicationservers',
            options={'ordering': ('server__name', 'application__name'), 'verbose_name': "3. Зв'язок Сервер - Сервіс", 'verbose_name_plural': "3. Зв'язок Сервер - Сервіс"},
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки'),
        ),
    ]
