# Generated by Django 4.1.7 on 2023-03-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_serverresponse_options_and_more'),
        ('info', '0013_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibleperson',
            options={'ordering': ('name',), 'verbose_name': 'Особи відповідальні за сервіс', 'verbose_name_plural': 'Особи відповідальні за сервіс'},
        ),
        migrations.AlterField(
            model_name='server',
            name='daemons',
            field=models.ManyToManyField(blank=True, related_name='servers', to='dictionary.serverservice', verbose_name='Сервіси (Services)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='*Примітки'),
        ),
        migrations.AlterField(
            model_name='server',
            name='external',
            field=models.BooleanField(default=False, verbose_name='*Опублікований в Інтернет'),
        ),
        migrations.AlterField(
            model_name='server',
            name='futures',
            field=models.ManyToManyField(blank=True, related_name='servers', to='dictionary.serverfuture', verbose_name='Ролі (Futures)'),
        ),
        migrations.AlterField(
            model_name='server',
            name='has_internet_access',
            field=models.BooleanField(default=False, verbose_name='*Має вихід в інтернет'),
        ),
        migrations.AlterField(
            model_name='server',
            name='has_monitoring_agent',
            field=models.BooleanField(default=False, verbose_name='*Відслідковується агентом'),
        ),
        migrations.AlterField(
            model_name='server',
            name='installed_soft',
            field=models.ManyToManyField(blank=True, related_name='servers', through='info.HostInstalledSoftware', to='dictionary.softwarecatalog', verbose_name='Встановлене ПО'),
        ),
        migrations.AlterField(
            model_name='server',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_uses', to='info.server', verbose_name='*Змінено на'),
        ),
        migrations.AlterField(
            model_name='server',
            name='scheduled_tasks',
            field=models.ManyToManyField(blank=True, related_name='task_servers', through='info.HostScheduledTask', to='dictionary.serverscheduledtask', verbose_name='Запланованы задачі'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.IntegerField(choices=[(0, 'Вимкнено'), (1, 'В роботі'), (2, 'Видалено'), (3, 'В резерві'), (4, 'Не ініціалізовано')], default=1, verbose_name='*Стан'),
        ),
        migrations.AlterField(
            model_name='server',
            name='virtual_server_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='*Ім`я виртуальної машини'),
        ),
        migrations.AlterField(
            model_name='server',
            name='win_rm_access',
            field=models.BooleanField(default=True, verbose_name='*WinRM доступ'),
        ),
    ]
