# Generated by Django 4.1.7 on 2023-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_alter_responsibleperson_options_alter_server_daemons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostscheduledtask',
            name='schedule',
        ),
        migrations.AddField(
            model_name='hostscheduledtask',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='hostscheduledtask',
            name='schedule_type',
            field=models.CharField(blank=True, default=None, max_length=10240, null=True, verbose_name='Планування'),
        ),
    ]
