# Generated by Django 4.2.5 on 2023-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_remove_hostscheduledtask_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostscheduledtask',
            name='schedule_type',
            field=models.CharField(blank=True, default=None, max_length=3072, null=True, verbose_name='Планування'),
        ),
    ]
