# Generated by Django 4.0.2 on 2022-02-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.DateTimeField(auto_now_add=True, verbose_name='Дата события')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнал',
            },
        ),
    ]
