# Generated by Django 4.0.2 on 2022-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermodificationlog',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servermodificationlog',
            name='seen',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
