# Generated by Django 4.0.2 on 2022-08-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0002_alter_servermodificationlog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermodificationlog',
            name='log_type',
            field=models.IntegerField(choices=[(0, 'DEBUG'), (1, 'Інформація'), (2, 'Попередження'), (3, 'Помилка'), (4, 'Тривога')], default=1, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='servermodificationlog',
            name='topic',
            field=models.IntegerField(choices=[(0, 'Інше'), (1, 'Задачі'), (2, 'Служби'), (3, 'ПО'), (4, 'Призначення'), (5, 'Роль'), (6, 'Сервіс'), (7, 'Система')], default=0, verbose_name='Розділ'),
        ),
    ]
