# Generated by Django 4.0.2 on 2022-09-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0003_servermodificationlog_log_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermodificationlog',
            name='log_type',
            field=models.IntegerField(choices=[(0, 'DEBUG'), (1, 'Інформація'), (2, 'Попередження'), (3, 'Помилка'), (4, 'Тривога'), (10, 'Встановлення'), (11, 'Оновлення'), (12, 'Видалення')], default=1, verbose_name='Тип'),
        ),
    ]
