# Generated by Django 4.1.7 on 2023-03-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_alter_responsibleperson_options_alter_server_daemons_and_more'),
        ('logview', '0005_alter_servermodificationlog_options_servertaskreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskControlGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва групи')),
                ('send_message', models.BooleanField(default=True, verbose_name='Формувати звіт про группу')),
            ],
            options={
                'verbose_name': 'Групи контролю автоматичних тасків',
                'verbose_name_plural': 'Групи контролю автоматичних тасків',
                'db_table': 'task_logger_taskcontrolgroup',
            },
        ),
        migrations.AddField(
            model_name='servertaskreport',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Код задачі для контролю'),
        ),
        migrations.CreateModel(
            name='TaskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код задачі для контролю')),
                ('period', models.IntegerField(default=1, verbose_name='Код завершення')),
                ('period_multiply', models.IntegerField(choices=[(86400, 'День'), (3600, 'Година'), (60, 'Хвилина'), (1, 'Секунда')], default=86400, verbose_name='')),
                ('status', models.IntegerField(blank=True, default=None, null=True, verbose_name='Код завершення')),
                ('message', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('last_execute', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Час останнього виконання')),
                ('last_control', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Час контрольної перевірки')),
                ('last_message', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Час сповіщення')),
                ('control_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_tasks', to='logview.taskcontrolgroup', verbose_name='Група завдань')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_tasks', to='info.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Контроль автоматичних тасків',
                'verbose_name_plural': 'Контроль автоматичних тасків',
                'db_table': 'task_logger_servertaskcontrol',
                'unique_together': {('code', 'host')},
            },
        ),
    ]
