# Generated by Django 4.1.7 on 2023-03-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0006_taskcontrolgroup_servertaskreport_code_taskcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontrol',
            name='notify_about_error',
            field=models.IntegerField(choices=[(0, 'Не сповіщати'), (1, 'Сопвіщувати по телеграм'), (1, 'Сповіщувати поштою'), (3, 'Всіма засобами сповіщення')], default=0, verbose_name='Сповіщати про помилки одразу'),
        ),
        migrations.AlterField(
            model_name='taskcontrol',
            name='period',
            field=models.IntegerField(default=1, verbose_name='Період'),
        ),
        migrations.AlterField(
            model_name='taskcontrol',
            name='period_multiply',
            field=models.IntegerField(choices=[(86400, 'День'), (3600, 'Година'), (60, 'Хвилина'), (1, 'Секунда')], default=86400, verbose_name='Одиниці виміру'),
        ),
    ]
