# Generated by Django 4.0.2 on 2022-04-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0006_alter_applicationserversspecification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(blank=True, null=True, verbose_name='Время')),
                ('info', models.CharField(max_length=250, verbose_name='Информация')),
                ('is_error', models.BooleanField(default=False, verbose_name='Ошибка')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='info.server', verbose_name='Сервер')),
            ],
        ),
    ]
