# Generated by Django 4.0.2 on 2023-02-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_logger', '0002_alter_servertaskreport_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerTaskReport',
        ),
    ]
