"""
Django settings for Inventarisation project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eis*6#=&no5k!5mr84^v7l!2b6cxm!tndq@fvm5t3#vy+*o5j+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dictionary',
    'info',
    'logview',
    'reports',
    'task_logger',
    'django_helpers',
    'sysinfo',
    'nested_admin',
    'baton.autodiscover',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.PersistentRemoteUserMiddleware',
    'dictionary.remote_user_backend.CustomRemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'dictionary.remote_user_backend.CustomUserBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'Inventarisation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inventarisation.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    '/var/www/static/',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BATON = {
    'SITE_HEADER': 'Inventory',
    'SITE_TITLE': 'Inventory',
    'INDEX_TITLE': 'Inventory Portal',
    'CHANGELIST_FILTERS_IN_MODAL': True,
    'CHANGELIST_FILTERS_FORM': True,
    'SUPPORT_HREF': '',
    'COPYRIGHT': '',
    'POWERED_BY': 'Manenok S.Y.',
    'HIDE_FOOTER': True,
    'MENU_TITLE': 'Меню',
    'MENU': (
        {
            'type': 'app',
            'name': 'reports',
            'label': 'Звіти',
            'icon': 'fa fa-circle-info',
        },
        {
            'type': 'app',
            'name': 'logview',
            'label': 'Журнал',
            'icon': 'fa fa-bug',
        },
        {
            'type': 'app',
            'name': 'info',
            'label': 'Редактор',
            'icon': 'fa fa-pen-to-square',
        },
        {
            'type': 'app',
            'name': 'dictionary',
            'label': 'Довідники',
            'icon': 'fa fa-spell-check',
        },
        {
            'type': 'app',
            'name': 'admin',
            'label': 'Адміністрування',
            'icon': 'fa fa-truck-fast',
        },

        {
            'type': 'app',
            'name': 'auth',
            'label': 'Користувачі',
            'icon': 'fa fa-lock',
        },
    ),
}

MAIL_SEND_REPORT={
    'server':'web01.local.erc',
    'port': 25,
    'from_mail': 'bspd@erc.ua',
    'to_mail': 'bspd@erc.ua',
}
